/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example

import org.openjdk.jmh.annotations.Measurement

//@Measurement
class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
   // org.openjdk.jmh.Main.main(args);
}
