/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example

import java.util.*

//@Measurement
object App {
    val greeting: String
        get() {
            return "Hello world."
        }

    fun main() {
        println(App.greeting)
    }

    fun methodToBeBenchmarked() {
        UUID.randomUUID()
    }

}

fun main(args: Array<String>) {
    App.main()
    //org.openjdk.jmh.Main.main(args);
}
